//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_DEFAULTS
    {
        public int ID { get; set; }
        public string DESCRIPTION { get; set; }
        public int DEFAULT_VALUE { get; set; }
        public string FROM_TABLE { get; set; }
    }
}
