//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckList_Master
    {
        public int PK_ItemID { get; set; }
        public int FK_CheckPointID { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual TBL_MP_Master_UserList TBL_MP_Master_UserList { get; set; }
    }
}
