//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesignationwiseDefaultRole
    {
        public int PK_MappingID { get; set; }
        public Nullable<int> FK_DesignationID { get; set; }
        public Nullable<int> Default_RoleID { get; set; }
    }
}
