//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EXCEL_ERP_TESTEntities : DbContext
    {
        public EXCEL_ERP_TESTEntities()
            : base("name=EXCEL_ERP_TESTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APP_DEFAULTS> APP_DEFAULTS { get; set; }
        public virtual DbSet<CheckList_Master> CheckList_Master { get; set; }
        public virtual DbSet<CompanyMaster> CompanyMasters { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Acct_Financial_Year> tbl_Acct_Financial_Year { get; set; }
        public virtual DbSet<TBL_ColorPreference> TBL_ColorPreference { get; set; }
        public virtual DbSet<TBL_MP_Admin_Branch_Master> TBL_MP_Admin_Branch_Master { get; set; }
        public virtual DbSet<TBL_MP_Admin_Category> TBL_MP_Admin_Category { get; set; }
        public virtual DbSet<TBL_MP_Admin_Company_Master> TBL_MP_Admin_Company_Master { get; set; }
        public virtual DbSet<TBL_MP_Admin_UserList> TBL_MP_Admin_UserList { get; set; }
        public virtual DbSet<TBL_MP_Admin_VoucherNoSetup> TBL_MP_Admin_VoucherNoSetup { get; set; }
        public virtual DbSet<TBL_MP_COMMON_Notification> TBL_MP_COMMON_Notification { get; set; }
        public virtual DbSet<TBL_MP_CRM_Followup_Master> TBL_MP_CRM_Followup_Master { get; set; }
        public virtual DbSet<TBL_MP_CRM_SalesEnquiry> TBL_MP_CRM_SalesEnquiry { get; set; }
        public virtual DbSet<TBL_MP_CRM_SalesEnquiry_Associates> TBL_MP_CRM_SalesEnquiry_Associates { get; set; }
        public virtual DbSet<TBL_MP_CRM_SalesEnquiry_Attachments> TBL_MP_CRM_SalesEnquiry_Attachments { get; set; }
        public virtual DbSet<TBL_MP_CRM_SalesEnquiry_BOQ> TBL_MP_CRM_SalesEnquiry_BOQ { get; set; }
        public virtual DbSet<TBL_MP_CRM_SalesOrder> TBL_MP_CRM_SalesOrder { get; set; }
        public virtual DbSet<TBL_MP_CRM_SalesOrder_Associates> TBL_MP_CRM_SalesOrder_Associates { get; set; }
        public virtual DbSet<TBL_MP_CRM_SalesOrder_Attachment> TBL_MP_CRM_SalesOrder_Attachment { get; set; }
        public virtual DbSet<TBL_MP_CRM_SalesOrder_BOQ> TBL_MP_CRM_SalesOrder_BOQ { get; set; }
        public virtual DbSet<TBL_MP_CRM_SalesOrder_ItemCharges> TBL_MP_CRM_SalesOrder_ItemCharges { get; set; }
        public virtual DbSet<TBL_MP_CRM_SalesOrder_TermsAndConditions> TBL_MP_CRM_SalesOrder_TermsAndConditions { get; set; }
        public virtual DbSet<TBL_MP_CRM_SalesQuestionnaire> TBL_MP_CRM_SalesQuestionnaire { get; set; }
        public virtual DbSet<TBL_MP_CRM_SalesQuotation> TBL_MP_CRM_SalesQuotation { get; set; }
        public virtual DbSet<TBL_MP_CRM_SalesQuotation_Associates> TBL_MP_CRM_SalesQuotation_Associates { get; set; }
        public virtual DbSet<TBL_MP_CRM_SalesQuotation_Attachments> TBL_MP_CRM_SalesQuotation_Attachments { get; set; }
        public virtual DbSet<TBL_MP_CRM_SalesQuotation_BOQ> TBL_MP_CRM_SalesQuotation_BOQ { get; set; }
        public virtual DbSet<TBL_MP_CRM_SalesQuotation_ItemCharges> TBL_MP_CRM_SalesQuotation_ItemCharges { get; set; }
        public virtual DbSet<TBL_MP_CRM_SalesQuotation_Review> TBL_MP_CRM_SalesQuotation_Review { get; set; }
        public virtual DbSet<TBL_MP_CRM_SalesQuotation_Review_Detail> TBL_MP_CRM_SalesQuotation_Review_Detail { get; set; }
        public virtual DbSet<TBL_MP_CRM_SalesQuotation_TermsAndConditions> TBL_MP_CRM_SalesQuotation_TermsAndConditions { get; set; }
        public virtual DbSet<TBL_MP_CRM_ScheduleCallLog> TBL_MP_CRM_ScheduleCallLog { get; set; }
        public virtual DbSet<TBL_MP_CRM_ScheduleCallLogAssignee> TBL_MP_CRM_ScheduleCallLogAssignee { get; set; }
        public virtual DbSet<TBL_MP_CRM_ScheduleCallLogFollowUp> TBL_MP_CRM_ScheduleCallLogFollowUp { get; set; }
        public virtual DbSet<TBL_MP_CRM_SM_ContactReferences> TBL_MP_CRM_SM_ContactReferences { get; set; }
        public virtual DbSet<TBL_MP_CRM_SM_DocumentHistory> TBL_MP_CRM_SM_DocumentHistory { get; set; }
        public virtual DbSet<TBL_MP_CRM_SM_SalesLead> TBL_MP_CRM_SM_SalesLead { get; set; }
        public virtual DbSet<TBL_MP_CRM_SM_SalesLead_Associates> TBL_MP_CRM_SM_SalesLead_Associates { get; set; }
        public virtual DbSet<TBL_MP_CRM_SM_SalesLead_Attachment> TBL_MP_CRM_SM_SalesLead_Attachment { get; set; }
        public virtual DbSet<TBL_MP_CRM_SM_SalesLead_SuspectingInfo> TBL_MP_CRM_SM_SalesLead_SuspectingInfo { get; set; }
        public virtual DbSet<TBL_MP_HR_AdvanceRequestApplication> TBL_MP_HR_AdvanceRequestApplication { get; set; }
        public virtual DbSet<TBL_MP_HR_DesignationwiseSalaryHeads> TBL_MP_HR_DesignationwiseSalaryHeads { get; set; }
        public virtual DbSet<TBL_MP_HR_HolidaysAndWeekOff> TBL_MP_HR_HolidaysAndWeekOff { get; set; }
        public virtual DbSet<TBL_MP_HR_LeaveApplication> TBL_MP_HR_LeaveApplication { get; set; }
        public virtual DbSet<TBL_MP_HR_LeaveConfiguration> TBL_MP_HR_LeaveConfiguration { get; set; }
        public virtual DbSet<TBl_MP_HR_LeaveEncashment_Log> TBl_MP_HR_LeaveEncashment_Log { get; set; }
        public virtual DbSet<TBL_MP_HR_LoanDisbursement> TBL_MP_HR_LoanDisbursement { get; set; }
        public virtual DbSet<TBL_MP_HR_LoanRequestApplication> TBL_MP_HR_LoanRequestApplication { get; set; }
        public virtual DbSet<TBL_MP_HR_ManualAttendance_Master> TBL_MP_HR_ManualAttendance_Master { get; set; }
        public virtual DbSet<TBL_MP_HR_PayslipMaster> TBL_MP_HR_PayslipMaster { get; set; }
        public virtual DbSet<TBl_MP_HR_SalaryHead> TBl_MP_HR_SalaryHead { get; set; }
        public virtual DbSet<TBL_MP_Master_Bank> TBL_MP_Master_Bank { get; set; }
        public virtual DbSet<TBL_MP_Master_BankBranch> TBL_MP_Master_BankBranch { get; set; }
        public virtual DbSet<TBL_MP_Master_Category> TBL_MP_Master_Category { get; set; }
        public virtual DbSet<TBL_MP_Master_City> TBL_MP_Master_City { get; set; }
        public virtual DbSet<TBL_MP_Master_Country> TBL_MP_Master_Country { get; set; }
        public virtual DbSet<TBL_MP_Master_Employee> TBL_MP_Master_Employee { get; set; }
        public virtual DbSet<TBL_MP_Master_Employee_Attachment> TBL_MP_Master_Employee_Attachment { get; set; }
        public virtual DbSet<TBL_MP_Master_Employee_Authority> TBL_MP_Master_Employee_Authority { get; set; }
        public virtual DbSet<TBL_MP_Master_Employee_CTC> TBL_MP_Master_Employee_CTC { get; set; }
        public virtual DbSet<TBL_MP_Master_Employee_LastEmployerDetail> TBL_MP_Master_Employee_LastEmployerDetail { get; set; }
        public virtual DbSet<TBL_MP_Master_Employee_LeaveConfiguration> TBL_MP_Master_Employee_LeaveConfiguration { get; set; }
        public virtual DbSet<TBL_MP_Master_Employee_MedicalDetail> TBL_MP_Master_Employee_MedicalDetail { get; set; }
        public virtual DbSet<TBL_MP_Master_Employee_PreviousEmployer> TBL_MP_Master_Employee_PreviousEmployer { get; set; }
        public virtual DbSet<TBL_MP_Master_Employee_Qualification> TBL_MP_Master_Employee_Qualification { get; set; }
        public virtual DbSet<TBL_MP_Master_Employee_Relative> TBL_MP_Master_Employee_Relative { get; set; }
        public virtual DbSet<TBL_MP_Master_Inventory_Category> TBL_MP_Master_Inventory_Category { get; set; }
        public virtual DbSet<TBL_MP_Master_Inventory_Level> TBL_MP_Master_Inventory_Level { get; set; }
        public virtual DbSet<TBL_MP_Master_Inventory_Level_Details> TBL_MP_Master_Inventory_Level_Details { get; set; }
        public virtual DbSet<TBL_MP_Master_Item> TBL_MP_Master_Item { get; set; }
        public virtual DbSet<TBL_MP_Master_Item_AssemblyChildItems> TBL_MP_Master_Item_AssemblyChildItems { get; set; }
        public virtual DbSet<TBL_MP_Master_Item_Attachments> TBL_MP_Master_Item_Attachments { get; set; }
        public virtual DbSet<TBL_MP_Master_Item_InvLevel_Details> TBL_MP_Master_Item_InvLevel_Details { get; set; }
        public virtual DbSet<TBL_MP_Master_Item_Suppliers> TBL_MP_Master_Item_Suppliers { get; set; }
        public virtual DbSet<Tbl_MP_Master_Module> Tbl_MP_Master_Module { get; set; }
        public virtual DbSet<Tbl_MP_Master_Module_Forms> Tbl_MP_Master_Module_Forms { get; set; }
        public virtual DbSet<Tbl_MP_Master_Party> Tbl_MP_Master_Party { get; set; }
        public virtual DbSet<Tbl_MP_Master_Party_Address> Tbl_MP_Master_Party_Address { get; set; }
        public virtual DbSet<Tbl_MP_Master_Party_BankDetail> Tbl_MP_Master_Party_BankDetail { get; set; }
        public virtual DbSet<Tbl_MP_Master_PartyContact_Detail> Tbl_MP_Master_PartyContact_Detail { get; set; }
        public virtual DbSet<TBL_MP_Master_Role> TBL_MP_Master_Role { get; set; }
        public virtual DbSet<TBL_MP_Master_RoleForm> TBL_MP_Master_RoleForm { get; set; }
        public virtual DbSet<TBL_MP_Master_RoleModule> TBL_MP_Master_RoleModule { get; set; }
        public virtual DbSet<TBL_MP_Master_State> TBL_MP_Master_State { get; set; }
        public virtual DbSet<TBL_MP_Master_TnC> TBL_MP_Master_TnC { get; set; }
        public virtual DbSet<TBL_MP_Master_UserList> TBL_MP_Master_UserList { get; set; }
        public virtual DbSet<TBL_MP_Master_Warehouse> TBL_MP_Master_Warehouse { get; set; }
        public virtual DbSet<TBL_MP_PMC_Project_CheckList> TBL_MP_PMC_Project_CheckList { get; set; }
        public virtual DbSet<TBL_MP_PMC_Project_Planning> TBL_MP_PMC_Project_Planning { get; set; }
        public virtual DbSet<TBL_MP_PMC_ProjectMaster> TBL_MP_PMC_ProjectMaster { get; set; }
        public virtual DbSet<TBL_User_CustomPermissions> TBL_User_CustomPermissions { get; set; }
        public virtual DbSet<TBL_User_Master> TBL_User_Master { get; set; }
        public virtual DbSet<DesignationwiseDefaultRole> DesignationwiseDefaultRoles { get; set; }
        public virtual DbSet<TBL_MP_Master_Area> TBL_MP_Master_Area { get; set; }
        public virtual DbSet<NTEST> NTESTs { get; set; }
        public virtual DbSet<ProjectParty> ProjectParties { get; set; }
        public virtual DbSet<vAdvanceRequestApplication> vAdvanceRequestApplications { get; set; }
        public virtual DbSet<vAttendanceRegister> vAttendanceRegisters { get; set; }
        public virtual DbSet<vEmployCTC> vEmployCTCs { get; set; }
        public virtual DbSet<vEmployee> vEmployees { get; set; }
        public virtual DbSet<vEMPLOYEE_DESCRIPTION> vEMPLOYEE_DESCRIPTION { get; set; }
        public virtual DbSet<vLeaveApplication> vLeaveApplications { get; set; }
        public virtual DbSet<vLoanRequestApplication> vLoanRequestApplications { get; set; }
        public virtual DbSet<vMasterItem> vMasterItems { get; set; }
        public virtual DbSet<vMasterParty> vMasterParties { get; set; }
        public virtual DbSet<vSalaryHead> vSalaryHeads { get; set; }
        public virtual DbSet<vSalesOrder> vSalesOrders { get; set; }
    
        public virtual ObjectResult<MXD_EMPLOYEE_LIST_Result> MXD_EMPLOYEE_LIST()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MXD_EMPLOYEE_LIST_Result>("MXD_EMPLOYEE_LIST");
        }
    
        public virtual ObjectResult<MXD_FOLLOWUPS_Result> MXD_FOLLOWUPS(string rEF_TYPE, Nullable<int> rEF_ID)
        {
            var rEF_TYPEParameter = rEF_TYPE != null ?
                new ObjectParameter("REF_TYPE", rEF_TYPE) :
                new ObjectParameter("REF_TYPE", typeof(string));
    
            var rEF_IDParameter = rEF_ID.HasValue ?
                new ObjectParameter("REF_ID", rEF_ID) :
                new ObjectParameter("REF_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MXD_FOLLOWUPS_Result>("MXD_FOLLOWUPS", rEF_TYPEParameter, rEF_IDParameter);
        }
    
        public virtual ObjectResult<MXD_GET_SCHEDULE_NOTIFICATION_FOR_USER_Result> MXD_GET_SCHEDULE_NOTIFICATION_FOR_USER(Nullable<int> employeeID)
        {
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MXD_GET_SCHEDULE_NOTIFICATION_FOR_USER_Result>("MXD_GET_SCHEDULE_NOTIFICATION_FOR_USER", employeeIDParameter);
        }
    
        public virtual ObjectResult<MXD_PLACES_LIST_Result> MXD_PLACES_LIST()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MXD_PLACES_LIST_Result>("MXD_PLACES_LIST");
        }
    
        public virtual int MXD_SALES_ORDER_LIST()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MXD_SALES_ORDER_LIST");
        }
    }
}
