//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTEST
    {
        public int PK_ProjectID { get; set; }
        public string ProjectNumber { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> SiteClientID { get; set; }
        public int SiteClientAddressID { get; set; }
        public string SiteAddress { get; set; }
        public Nullable<int> BillingClientID { get; set; }
        public int BillingClientAddressID { get; set; }
        public string BillingAddress { get; set; }
        public System.DateTime ProjectDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int FK_YearID { get; set; }
        public int FK_BranchID { get; set; }
        public int FK_CompanyID { get; set; }
    }
}
