//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MP_Master_PartyContact_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_MP_Master_PartyContact_Detail()
        {
            this.TBL_MP_CRM_SM_ContactReferences = new HashSet<TBL_MP_CRM_SM_ContactReferences>();
        }
    
        public int PK_PartyContactDetails { get; set; }
        public Nullable<int> FK_PartyID { get; set; }
        public string ContactPersoneName { get; set; }
        public Nullable<int> ContactType { get; set; }
        public string ContactType_Text { get; set; }
        public Nullable<int> FK_Department { get; set; }
        public string FK_Department_Text { get; set; }
        public Nullable<int> FK_Designation { get; set; }
        public string FK_Designation_Text { get; set; }
        public string Address { get; set; }
        public string TelephoneNo { get; set; }
        public string AltTelephoneNo { get; set; }
        public string MobileNo { get; set; }
        public string AltMobileNo { get; set; }
        public string FaxNo { get; set; }
        public string EmailID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeleteDateTime { get; set; }
        public string DeleteRemarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_CRM_SM_ContactReferences> TBL_MP_CRM_SM_ContactReferences { get; set; }
        public virtual Tbl_MP_Master_Party Tbl_MP_Master_Party { get; set; }
    }
}
