//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_CRM_SalesQuotation_TermsAndConditions
    {
        public int PK_Quotation_TermID { get; set; }
        public Nullable<int> FK_Quotation_ID { get; set; }
        public string Term_Title { get; set; }
        public string Term_Description { get; set; }
        public Nullable<int> Sequence { get; set; }
    }
}
