//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_CRM_SalesQuotation_Associates
    {
        public int PK_SalesQuotationAssociatesID { get; set; }
        public int FK_SalesQuotationID { get; set; }
        public int FK_EmployeeID { get; set; }
        public System.DateTime AssignDate { get; set; }
    
        public virtual TBL_MP_CRM_SalesQuotation TBL_MP_CRM_SalesQuotation { get; set; }
        public virtual TBL_MP_Master_Employee TBL_MP_Master_Employee { get; set; }
    }
}
