//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_Admin_UserList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MP_Admin_UserList()
        {
            this.TBL_MP_Master_Item = new HashSet<TBL_MP_Master_Item>();
            this.TBL_MP_CRM_SalesOrder_TermsAndConditions = new HashSet<TBL_MP_CRM_SalesOrder_TermsAndConditions>();
            this.TBL_MP_CRM_ScheduleCallLogFollowUp = new HashSet<TBL_MP_CRM_ScheduleCallLogFollowUp>();
            this.TBL_MP_HR_AdvanceRequestApplication = new HashSet<TBL_MP_HR_AdvanceRequestApplication>();
            this.TBL_MP_HR_DesignationwiseSalaryHeads = new HashSet<TBL_MP_HR_DesignationwiseSalaryHeads>();
            this.TBL_MP_HR_LeaveApplication = new HashSet<TBL_MP_HR_LeaveApplication>();
            this.TBL_MP_HR_LeaveConfiguration = new HashSet<TBL_MP_HR_LeaveConfiguration>();
            this.TBL_MP_HR_LoanDisbursement = new HashSet<TBL_MP_HR_LoanDisbursement>();
            this.TBL_MP_HR_LoanRequestApplication = new HashSet<TBL_MP_HR_LoanRequestApplication>();
            this.TBL_MP_Master_Employee_LeaveConfiguration = new HashSet<TBL_MP_Master_Employee_LeaveConfiguration>();
            this.TBL_MP_Master_Employee_MedicalDetail = new HashSet<TBL_MP_Master_Employee_MedicalDetail>();
            this.TBL_MP_Master_Employee_Relative = new HashSet<TBL_MP_Master_Employee_Relative>();
            this.Tbl_MP_Master_Party_BankDetail = new HashSet<Tbl_MP_Master_Party_BankDetail>();
            this.TBL_MP_Master_TnC = new HashSet<TBL_MP_Master_TnC>();
        }
    
        public int PKID { get; set; }
        public int Fk_Admin_CategoryID { get; set; }
        public string Admin_UserList_Desc { get; set; }
        public string ShortCode { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
    
        public virtual TBL_MP_Admin_Category TBL_MP_Admin_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_Item> TBL_MP_Master_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_CRM_SalesOrder_TermsAndConditions> TBL_MP_CRM_SalesOrder_TermsAndConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_CRM_ScheduleCallLogFollowUp> TBL_MP_CRM_ScheduleCallLogFollowUp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_HR_AdvanceRequestApplication> TBL_MP_HR_AdvanceRequestApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_HR_DesignationwiseSalaryHeads> TBL_MP_HR_DesignationwiseSalaryHeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_HR_LeaveApplication> TBL_MP_HR_LeaveApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_HR_LeaveConfiguration> TBL_MP_HR_LeaveConfiguration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_HR_LoanDisbursement> TBL_MP_HR_LoanDisbursement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_HR_LoanRequestApplication> TBL_MP_HR_LoanRequestApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_Employee_LeaveConfiguration> TBL_MP_Master_Employee_LeaveConfiguration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_Employee_MedicalDetail> TBL_MP_Master_Employee_MedicalDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_Employee_Relative> TBL_MP_Master_Employee_Relative { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MP_Master_Party_BankDetail> Tbl_MP_Master_Party_BankDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_TnC> TBL_MP_Master_TnC { get; set; }
    }
}
