//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_Master_RoleModule
    {
        public int PK_RoleModuleID { get; set; }
        public int FK_RoleId { get; set; }
        public int FK_ModuleId { get; set; }
        public Nullable<bool> Access { get; set; }
        public Nullable<int> Fk_BranchId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeleteDatetime { get; set; }
        public string DeleteRemarks { get; set; }
    
        public virtual Tbl_MP_Master_Module Tbl_MP_Master_Module { get; set; }
        public virtual TBL_MP_Master_Role TBL_MP_Master_Role { get; set; }
    }
}
