//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_Master_Employee_LastEmployerDetail
    {
        public int LastEmployerID { get; set; }
        public bool isActive { get; set; }
        public int FK_EmployeeId { get; set; }
        public string LastEmployerName { get; set; }
        public string Address { get; set; }
        public Nullable<int> ContactNo { get; set; }
    
        public virtual TBL_MP_Master_Employee TBL_MP_Master_Employee { get; set; }
        public virtual TBL_MP_Master_Employee_LastEmployerDetail TBL_MP_Master_Employee_LastEmployerDetail1 { get; set; }
        public virtual TBL_MP_Master_Employee_LastEmployerDetail TBL_MP_Master_Employee_LastEmployerDetail2 { get; set; }
    }
}
