//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_Master_Employee_LeaveConfiguration
    {
        public int PK_LeaveID { get; set; }
        public int FK_EmployeeID { get; set; }
        public int FK_LeaveTypeID { get; set; }
        public int FK_BranchID { get; set; }
        public int FK_FinYearID { get; set; }
        public decimal MaxDaysAllow { get; set; }
        public bool CarryForwardLeave { get; set; }
        public decimal CarryForwardLimitDays { get; set; }
        public decimal LeavesEarned { get; set; }
        public bool ApplicableInProbation { get; set; }
        public bool LeaveEnchashable { get; set; }
        public string EncashableSalaryHeadIDs { get; set; }
        public string EncashableSalaryHeadNames { get; set; }
        public bool IsActive { get; set; }
    
        public virtual TBL_MP_Admin_UserList TBL_MP_Admin_UserList { get; set; }
        public virtual TBL_MP_Master_Employee TBL_MP_Master_Employee { get; set; }
    }
}
