//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_Master_Item_InvLevel_Details
    {
        public int Pk_Item_Inv_Level_DetailsID { get; set; }
        public Nullable<int> Fk_ItemID { get; set; }
        public Nullable<int> Fk_InvLevel_Dtls_ID { get; set; }
    }
}
