//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_HR_AdvanceRequestApplication
    {
        public int PK_AdvancRequestID { get; set; }
        public string AdvanceRequestNo { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int FK_EmployeeID { get; set; }
        public decimal RequestedAmount { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public string Remarks { get; set; }
        public int ApprovalStatus { get; set; }
        public int FK_RequestTo { get; set; }
        public Nullable<int> FK_ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<decimal> ApprovedAmount { get; set; }
        public string RemarksApproved { get; set; }
        public int Fk_BranchID { get; set; }
        public int Fk_YearID { get; set; }
        public int FK_CompanyID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual TBL_MP_Admin_UserList TBL_MP_Admin_UserList { get; set; }
        public virtual TBL_MP_Master_Employee TBL_MP_Master_Employee { get; set; }
    }
}
