//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBl_MP_HR_LeaveEncashment_Log
    {
        public int PK_LeaveEncashID { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> FK_EmployeeID { get; set; }
        public Nullable<int> FK_LeaveTypeID { get; set; }
        public Nullable<int> NoOfDays { get; set; }
        public Nullable<int> FK_EnashmentStatusID { get; set; }
        public Nullable<System.DateTime> DisbursedDate { get; set; }
        public string RemarksRequest { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string ApprovalRemarks { get; set; }
        public Nullable<int> DisburseBy { get; set; }
        public Nullable<System.DateTime> DisburseDate { get; set; }
        public string DisburseRemarks { get; set; }
        public bool IsActive { get; set; }
    }
}
