//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_CRM_SalesQuotation_BOQ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MP_CRM_SalesQuotation_BOQ()
        {
            this.TBL_MP_CRM_SalesQuotation_ItemCharges = new HashSet<TBL_MP_CRM_SalesQuotation_ItemCharges>();
        }
    
        public int QUOTE_BOQ_ID { get; set; }
        public string BOQ_NUMBER { get; set; }
        public int QUOTE_ID { get; set; }
        public string BOQ_OBJECT { get; set; }
        public Nullable<int> BOQ_CREATED_BY { get; set; }
        public Nullable<System.DateTime> BOQ_CREATED_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_CRM_SalesQuotation_ItemCharges> TBL_MP_CRM_SalesQuotation_ItemCharges { get; set; }
    }
}
