//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_Master_Employee_PreviousEmployer
    {
        public int Pk_ResumePosPrevEmpmnt { get; set; }
        public Nullable<int> fk_ResumePostingId { get; set; }
        public Nullable<System.DateTime> PrvEmpmntFromDate { get; set; }
        public string PrvEmpmntNameAddOfEmployer { get; set; }
        public string PrvEmpmntPostHeldResponsb { get; set; }
        public string PrvEmpmntReasonLeaving { get; set; }
        public Nullable<System.DateTime> PrvEmpmntToDate { get; set; }
        public Nullable<byte> IsActive { get; set; }
    }
}
