//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_CRM_ScheduleCallLogFollowUp
    {
        public int FollowUpID { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string FollowUpRemark { get; set; }
        public Nullable<int> FollowUpStatus { get; set; }
        public Nullable<System.DateTime> FollowUpDateTime { get; set; }
        public Nullable<bool> NextFollowupRequired { get; set; }
        public Nullable<System.DateTime> NextFollowUpStartDatetime { get; set; }
        public Nullable<System.DateTime> NextFollowUpEndDatetime { get; set; }
        public Nullable<System.DateTime> NextFollowUpRemainder { get; set; }
        public string NextFollowUpSubject { get; set; }
        public string NextFollowUpContactName { get; set; }
        public string NextFollowUpContactNumber { get; set; }
        public string NextFollowUpLocation { get; set; }
        public Nullable<int> FollowUpSequence { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDatetime { get; set; }
        public string ReasonClose { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteDateTime { get; set; }
        public string DeleteRemarks { get; set; }
    
        public virtual TBL_MP_Admin_UserList TBL_MP_Admin_UserList { get; set; }
        public virtual TBL_MP_CRM_ScheduleCallLog TBL_MP_CRM_ScheduleCallLog { get; set; }
        public virtual TBL_MP_Master_Employee TBL_MP_Master_Employee { get; set; }
    }
}
