//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_CRM_SM_SalesLead_Associates
    {
        public int PK_SalesLeadAssociatesID { get; set; }
        public Nullable<int> FK_SalesLeadID { get; set; }
        public Nullable<int> FK_EmployeeID { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public Nullable<System.DateTime> ViewDateTime { get; set; }
    
        public virtual TBL_MP_CRM_SM_SalesLead TBL_MP_CRM_SM_SalesLead { get; set; }
        public virtual TBL_MP_Master_Employee TBL_MP_Master_Employee { get; set; }
    }
}
