//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_PMC_Project_Planning
    {
        public int PK_ProjectPlanID { get; set; }
        public int FK_ProjectID { get; set; }
        public byte[] ProjectPlan { get; set; }
        public int ProjectPlanType { get; set; }
        public Nullable<int> LockedByEmployee { get; set; }
    
        public virtual TBL_MP_PMC_ProjectMaster TBL_MP_PMC_ProjectMaster { get; set; }
    }
}
