//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_Master_Area
    {
        public int PK_AreaID { get; set; }
        public string AreaCode { get; set; }
        public string AreaName { get; set; }
        public string PinCode { get; set; }
        public int Fk_CityID { get; set; }
        public int IsActive { get; set; }
        public int FK_CompanyID { get; set; }
        public int FK_BranchID { get; set; }
    }
}
