//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_Admin_VoucherNoSetup
    {
        public int PK_VoucherSetupID { get; set; }
        public string NoPrefix { get; set; }
        public string NoPostfix { get; set; }
        public string NoSeperator { get; set; }
        public Nullable<int> NoStartingFrom { get; set; }
        public bool Is_NoContinuedNextYear { get; set; }
        public Nullable<System.DateTime> Effect_From_Date { get; set; }
        public Nullable<bool> Is_Lock_PrevEntries { get; set; }
        public int NoPad { get; set; }
        public int fk_FormID { get; set; }
        public string VoucherNoPreview { get; set; }
        public Nullable<int> Fk_BranchID { get; set; }
        public int Fk_YearID { get; set; }
        public Nullable<int> FK_PreparedBy { get; set; }
        public Nullable<int> FK_ApprovedBy { get; set; }
        public Nullable<int> FK_CheckedBy { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    }
}
