//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_HR_LeaveApplication
    {
        public int PK_LeaveApplicationID { get; set; }
        public string ApplicationNo { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public int FK_UserList_LeaveFormTypeID { get; set; }
        public int FK_EmployeeID { get; set; }
        public int fK_UsrLst_LeaveTypeID { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<System.DateTime> FromTime { get; set; }
        public Nullable<System.DateTime> ToTime { get; set; }
        public string Duration { get; set; }
        public string Remarks { get; set; }
        public int PreparedBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<System.DateTime> Approval_Date { get; set; }
        public int FK_UserList_ApprovalStatusID { get; set; }
        public int FK_RequestTo { get; set; }
        public Nullable<int> FK_ApprovedBy { get; set; }
        public string RemarksApproval { get; set; }
        public int FK_BranchID { get; set; }
        public int FK_CompanyID { get; set; }
        public int FK_YearID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual TBL_MP_Admin_UserList TBL_MP_Admin_UserList { get; set; }
        public virtual TBL_MP_Master_Employee TBL_MP_Master_Employee { get; set; }
    }
}
