//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MP_Master_Party_Address
    {
        public int PK_AddressID { get; set; }
        public int FK_PartyID { get; set; }
        public string Address { get; set; }
        public int FK_CountryID { get; set; }
        public int FK_StateID { get; set; }
        public int FK_CityID { get; set; }
        public string PIN_Code { get; set; }
        public bool IsActive { get; set; }
    
        public virtual TBL_MP_Master_City TBL_MP_Master_City { get; set; }
        public virtual TBL_MP_Master_Country TBL_MP_Master_Country { get; set; }
        public virtual Tbl_MP_Master_Party Tbl_MP_Master_Party { get; set; }
        public virtual TBL_MP_Master_State TBL_MP_Master_State { get; set; }
    }
}
