//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_CRM_SM_SalesLead_SuspectingInfo
    {
        public int PK_SuspectingID { get; set; }
        public Nullable<int> FK_SalesLeadID { get; set; }
        public Nullable<int> FK_SuspectCategory { get; set; }
        public string Brief_Description { get; set; }
    
        public virtual TBL_MP_CRM_SM_SalesLead TBL_MP_CRM_SM_SalesLead { get; set; }
    }
}
