//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_Master_Item_Suppliers
    {
        public int PK_RelationID { get; set; }
        public Nullable<int> FK_SupplierID { get; set; }
        public Nullable<int> Fk_ItemID { get; set; }
        public Nullable<int> LeadTimeInDays { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
        public Nullable<int> FK_CategoryID { get; set; }
    
        public virtual TBL_MP_Master_Inventory_Category TBL_MP_Master_Inventory_Category { get; set; }
        public virtual TBL_MP_Master_Item TBL_MP_Master_Item { get; set; }
        public virtual Tbl_MP_Master_Party Tbl_MP_Master_Party { get; set; }
    }
}
