//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_CRM_SalesOrder_ItemCharges
    {
        public int PK_ItemChargesID { get; set; }
        public int FK_OrderID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int FK_PartyID { get; set; }
        public int FK_ORDER_BOQID { get; set; }
        public string SheetName { get; set; }
        public Nullable<int> FK_ItemID { get; set; }
        public int Item_IndexID { get; set; }
        public decimal Item_Quantity { get; set; }
        public decimal MaterialBasicPrice { get; set; }
        public int MaterialAddOnChargesType { get; set; }
        public decimal MaterialAddOnChargesValue { get; set; }
        public decimal MaterialAddOnChargesAmount { get; set; }
        public int MaterialProfitMarginType { get; set; }
        public decimal MaterialProfitMarginValue { get; set; }
        public decimal MaterialProfitMarginAmount { get; set; }
        public decimal MaterialSellingCost { get; set; }
        public int MaterialDiscountType { get; set; }
        public decimal MaterialDiscountValue { get; set; }
        public decimal MaterialDiscountAmount { get; set; }
        public decimal Material_SGST_Percent { get; set; }
        public decimal Material_SGST_Amount { get; set; }
        public decimal Material_CGST_Percent { get; set; }
        public decimal Material_CGST_Amount { get; set; }
        public decimal Material_IGST_Percent { get; set; }
        public decimal Material_IGST_Amount { get; set; }
        public decimal Material_GST_Amount { get; set; }
        public decimal MaterialNetRate { get; set; }
        public decimal MaterialSupplyAmount { get; set; }
        public int InstallationRateType { get; set; }
        public decimal InstallationRateValue { get; set; }
        public decimal InstallationRateAmount { get; set; }
        public int InstallationAddOnChargesType { get; set; }
        public decimal InstallationAddOnChargesValue { get; set; }
        public decimal InstallationAddOnChargesAmount { get; set; }
        public int InstallationProfitMarginType { get; set; }
        public decimal InstallationProfitMarginValue { get; set; }
        public decimal InstallationProfitMarginAmount { get; set; }
        public decimal InstallationSellingCost { get; set; }
        public int InstallationDiscountType { get; set; }
        public decimal InstallationDiscountValue { get; set; }
        public decimal InstallationDiscountAmount { get; set; }
        public decimal Installation_SGST_Percent { get; set; }
        public decimal Installatiion_SGST_Amount { get; set; }
        public decimal Installation_CGST_Percent { get; set; }
        public decimal Installation_CGST_Amount { get; set; }
        public decimal Installation_IGST_Percent { get; set; }
        public decimal Installation_IGST_Amount { get; set; }
        public decimal Installation_GST_Amount { get; set; }
        public decimal InstallationNetRate { get; set; }
        public decimal InstallationAmount { get; set; }
    
        public virtual TBL_MP_CRM_SalesOrder_BOQ TBL_MP_CRM_SalesOrder_BOQ { get; set; }
        public virtual TBL_MP_Master_Item TBL_MP_Master_Item { get; set; }
        public virtual Tbl_MP_Master_Party Tbl_MP_Master_Party { get; set; }
    }
}
