//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_Master_Inventory_Level
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MP_Master_Inventory_Level()
        {
            this.TBL_MP_Master_Inventory_Level_Details = new HashSet<TBL_MP_Master_Inventory_Level_Details>();
        }
    
        public int Pk_Inv_Level_ID { get; set; }
        public Nullable<int> Fk_InvCategory_ID { get; set; }
        public string Inventory_Level { get; set; }
        public Nullable<int> Sequence { get; set; }
        public bool IsActive { get; set; }
    
        public virtual TBL_MP_Master_Inventory_Category TBL_MP_Master_Inventory_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_Inventory_Level_Details> TBL_MP_Master_Inventory_Level_Details { get; set; }
    }
}
