//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_CRM_SalesQuotation_Review
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MP_CRM_SalesQuotation_Review()
        {
            this.TBL_MP_CRM_SalesQuotation_Review_Detail = new HashSet<TBL_MP_CRM_SalesQuotation_Review_Detail>();
        }
    
        public int PK_ReviewID { get; set; }
        public int FK_QuotationID { get; set; }
        public string ReviewName { get; set; }
        public string FinalNote { get; set; }
    
        public virtual TBL_MP_CRM_SalesQuotation TBL_MP_CRM_SalesQuotation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_CRM_SalesQuotation_Review_Detail> TBL_MP_CRM_SalesQuotation_Review_Detail { get; set; }
    }
}
