//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_Master_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MP_Master_Employee()
        {
            this.TBL_MP_COMMON_Notification = new HashSet<TBL_MP_COMMON_Notification>();
            this.TBL_MP_CRM_SalesEnquiry_Associates = new HashSet<TBL_MP_CRM_SalesEnquiry_Associates>();
            this.TBL_MP_CRM_SalesQuotation_Associates = new HashSet<TBL_MP_CRM_SalesQuotation_Associates>();
            this.TBL_MP_CRM_ScheduleCallLogAssignee = new HashSet<TBL_MP_CRM_ScheduleCallLogAssignee>();
            this.TBL_MP_CRM_ScheduleCallLogFollowUp = new HashSet<TBL_MP_CRM_ScheduleCallLogFollowUp>();
            this.TBL_MP_CRM_SM_SalesLead_Associates = new HashSet<TBL_MP_CRM_SM_SalesLead_Associates>();
            this.TBL_MP_HR_AdvanceRequestApplication = new HashSet<TBL_MP_HR_AdvanceRequestApplication>();
            this.TBL_MP_HR_LeaveApplication = new HashSet<TBL_MP_HR_LeaveApplication>();
            this.TBL_MP_HR_LoanDisbursement = new HashSet<TBL_MP_HR_LoanDisbursement>();
            this.TBL_MP_HR_LoanRequestApplication = new HashSet<TBL_MP_HR_LoanRequestApplication>();
            this.TBL_MP_HR_ManualAttendance_Master = new HashSet<TBL_MP_HR_ManualAttendance_Master>();
            this.TBL_MP_HR_PayslipMaster = new HashSet<TBL_MP_HR_PayslipMaster>();
            this.TBL_MP_Master_Employee_Attachment = new HashSet<TBL_MP_Master_Employee_Attachment>();
            this.TBL_MP_Master_Employee_LastEmployerDetail = new HashSet<TBL_MP_Master_Employee_LastEmployerDetail>();
            this.TBL_MP_Master_Employee_LeaveConfiguration = new HashSet<TBL_MP_Master_Employee_LeaveConfiguration>();
            this.TBL_MP_Master_Employee_MedicalDetail = new HashSet<TBL_MP_Master_Employee_MedicalDetail>();
            this.TBL_MP_Master_Employee_Qualification = new HashSet<TBL_MP_Master_Employee_Qualification>();
            this.TBL_MP_Master_Employee_Relative = new HashSet<TBL_MP_Master_Employee_Relative>();
            this.TBL_MP_Master_Warehouse = new HashSet<TBL_MP_Master_Warehouse>();
            this.TBL_User_CustomPermissions = new HashSet<TBL_User_CustomPermissions>();
            this.TBL_User_Master = new HashSet<TBL_User_Master>();
        }
    
        public int PK_EmployeeId { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public string CompEmpID { get; set; }
        public Nullable<int> fk_UL_Cat_Id { get; set; }
        public int FK_EmploymentTypeID { get; set; }
        public string Alias { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<int> FK_DepartmentId { get; set; }
        public Nullable<int> FK_DesignationId { get; set; }
        public string PhoneNo1 { get; set; }
        public string AltPhoneNo { get; set; }
        public string EmailAddress { get; set; }
        public string fk_Branch_BranchID { get; set; }
        public Nullable<int> fk_Branch_MainBranch { get; set; }
        public Nullable<int> MaxID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DateOfAppointmnet { get; set; }
        public Nullable<System.DateTime> DateOfJoinig { get; set; }
        public Nullable<double> ProbationPeriod { get; set; }
        public Nullable<double> NoticePeriod { get; set; }
        public string ResidentialAddress { get; set; }
        public Nullable<bool> IsResigned { get; set; }
        public Nullable<System.DateTime> ResignedDate { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public string ReasonForResigning { get; set; }
        public Nullable<bool> HoldSalary { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string BirthPlace { get; set; }
        public Nullable<int> fk_UL_Gender_Id { get; set; }
        public Nullable<int> FK_UL_BloodGroup_ID { get; set; }
        public Nullable<int> FK_UL_MaritalStatus_ID { get; set; }
        public Nullable<System.DateTime> AnniversaryDate { get; set; }
        public string Language { get; set; }
        public Nullable<int> FK_BankID { get; set; }
        public Nullable<int> FK_BankBranchID { get; set; }
        public Nullable<int> fk_UL_AccType_Id { get; set; }
        public string AccountNo { get; set; }
        public string ATMNo { get; set; }
        public string CreditCardNo { get; set; }
        public string PFNo { get; set; }
        public string ESICNo { get; set; }
        public Nullable<System.DateTime> DateOfLastMedicalCheckUp { get; set; }
        public Nullable<System.DateTime> DueDateOfNextMedicalCheckUp { get; set; }
        public Nullable<bool> IsPFApplicable { get; set; }
        public Nullable<bool> IsESICApplicable { get; set; }
        public Nullable<int> fk_CTCId { get; set; }
        public Nullable<decimal> CTCValue { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string CTCSpecialNotes { get; set; }
        public string LastEmployerName { get; set; }
        public string LastEmployerAddress { get; set; }
        public string LastEmployerConNo { get; set; }
        public Nullable<byte> IsFnf_Flag { get; set; }
        public Nullable<int> B2BLogin { get; set; }
        public Nullable<int> FK_AgentID { get; set; }
        public string PanNo { get; set; }
        public string UniqueIdNo { get; set; }
        public string Nationality { get; set; }
        public string PassportNo { get; set; }
        public Nullable<System.DateTime> PassportIssueDate { get; set; }
        public Nullable<System.DateTime> PassportExpiryDate { get; set; }
        public Nullable<int> Fk_VisaType { get; set; }
        public Nullable<System.DateTime> VisaIssueDate { get; set; }
        public Nullable<System.DateTime> VisaExpiryDate { get; set; }
        public string LicenceNo { get; set; }
        public Nullable<System.DateTime> LicenceIssueDate { get; set; }
        public Nullable<System.DateTime> LicenceExpiryDate { get; set; }
        public string Fk_WorkPermityType { get; set; }
        public Nullable<System.DateTime> WorkPermitIssueDate { get; set; }
        public Nullable<System.DateTime> WorkPermitExpiryDate { get; set; }
        public string WorkPermit { get; set; }
        public Nullable<int> Fk_AirFare { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public string VisaNo { get; set; }
        public Nullable<double> VPFPer { get; set; }
        public Nullable<double> VPFCalculatedAmount { get; set; }
        public string Attachment { get; set; }
        public Nullable<bool> SeniorCitizen { get; set; }
        public string PermanentAddress { get; set; }
        public string IFSCCode { get; set; }
        public string UANNo { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> ModeOfPayment { get; set; }
        public Nullable<bool> isActive { get; set; }
        public int FK_CompanyID { get; set; }
        public int FK_YearID { get; set; }
        public int FK_BranchID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<int> JoiningLocationCityID { get; set; }
        public Nullable<int> FK_BossID { get; set; }
        public string WeekOffDays { get; set; }
        public string OfficePhoneNo { get; set; }
        public string OfficeEmailAddr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_COMMON_Notification> TBL_MP_COMMON_Notification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_CRM_SalesEnquiry_Associates> TBL_MP_CRM_SalesEnquiry_Associates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_CRM_SalesQuotation_Associates> TBL_MP_CRM_SalesQuotation_Associates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_CRM_ScheduleCallLogAssignee> TBL_MP_CRM_ScheduleCallLogAssignee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_CRM_ScheduleCallLogFollowUp> TBL_MP_CRM_ScheduleCallLogFollowUp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_CRM_SM_SalesLead_Associates> TBL_MP_CRM_SM_SalesLead_Associates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_HR_AdvanceRequestApplication> TBL_MP_HR_AdvanceRequestApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_HR_LeaveApplication> TBL_MP_HR_LeaveApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_HR_LoanDisbursement> TBL_MP_HR_LoanDisbursement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_HR_LoanRequestApplication> TBL_MP_HR_LoanRequestApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_HR_ManualAttendance_Master> TBL_MP_HR_ManualAttendance_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_HR_PayslipMaster> TBL_MP_HR_PayslipMaster { get; set; }
        public virtual TBL_MP_Master_Bank TBL_MP_Master_Bank { get; set; }
        public virtual TBL_MP_Master_BankBranch TBL_MP_Master_BankBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_Employee_Attachment> TBL_MP_Master_Employee_Attachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_Employee_LastEmployerDetail> TBL_MP_Master_Employee_LastEmployerDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_Employee_LeaveConfiguration> TBL_MP_Master_Employee_LeaveConfiguration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_Employee_MedicalDetail> TBL_MP_Master_Employee_MedicalDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_Employee_Qualification> TBL_MP_Master_Employee_Qualification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_Employee_Relative> TBL_MP_Master_Employee_Relative { get; set; }
        public virtual TBL_MP_Master_Employee TBL_MP_Master_Employee1 { get; set; }
        public virtual TBL_MP_Master_Employee TBL_MP_Master_Employee2 { get; set; }
        public virtual TBL_MP_Master_Employee TBL_MP_Master_Employee11 { get; set; }
        public virtual TBL_MP_Master_Employee TBL_MP_Master_Employee3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_Warehouse> TBL_MP_Master_Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_User_CustomPermissions> TBL_User_CustomPermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_User_Master> TBL_User_Master { get; set; }
    }
}
