//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_Master_Item_AssemblyChildItems
    {
        public int PK_AssemblyChildID { get; set; }
        public int AssemblyItemID { get; set; }
        public int AssemblyChildItemID { get; set; }
        public Nullable<decimal> DefaultQty { get; set; }
    
        public virtual TBL_MP_Master_Item TBL_MP_Master_Item { get; set; }
    }
}
