//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_HR_ManualAttendance_Master
    {
        public int PK_AttendanceID { get; set; }
        public int FK_EmployeeID { get; set; }
        public System.DateTime AttendStdInTime { get; set; }
        public System.DateTime AttendStdOutTime { get; set; }
        public System.DateTime AttendDate { get; set; }
        public Nullable<int> FK_CostCenterId { get; set; }
        public System.DateTime AttendInTime { get; set; }
        public System.DateTime AttendOutTime { get; set; }
        public string Duration { get; set; }
        public int AttendanceType { get; set; }
        public string AttendanceRemarks { get; set; }
        public Nullable<int> FK_LeaveApplicationID { get; set; }
        public Nullable<int> FK_LeaveTypeID { get; set; }
        public bool AtWarehouse { get; set; }
        public int FK_CompanyId { get; set; }
        public int FK_BranchId { get; set; }
        public int FK_YearId { get; set; }
        public bool IsActive { get; set; }
        public int FK_PreparedBy { get; set; }
        public Nullable<int> FK_ApprovedBy { get; set; }
        public Nullable<int> FK_CheckedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<bool> isSelected { get; set; }
        public Nullable<bool> isLeaveRejected { get; set; }
    
        public virtual TBL_MP_Master_Employee TBL_MP_Master_Employee { get; set; }
        public virtual TBL_MP_PMC_ProjectMaster TBL_MP_PMC_ProjectMaster { get; set; }
    }
}
