//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ColorPreference
    {
        public int PK_ID { get; set; }
        public Nullable<int> FK_EmployeeID { get; set; }
        public string ColorPresent { get; set; }
        public string ColorAbsent { get; set; }
        public string ColorLeave { get; set; }
        public string ColorOutdoor { get; set; }
        public string ColorCompOff { get; set; }
        public string ColorLateComing { get; set; }
        public string ColorEarlyLeaving { get; set; }
        public string ColorHoliday { get; set; }
        public string ColorWeekOff { get; set; }
        public string ColorDuplicates { get; set; }
    }
}
