//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_HR_LoanDisbursement
    {
        public int PK_LoanDisbursementID { get; set; }
        public System.DateTime DisbursementDate { get; set; }
        public int FK_LoanRequestID { get; set; }
        public int FK_EmployeeID { get; set; }
        public decimal LoanAmount { get; set; }
        public decimal InterestRate { get; set; }
        public decimal InstallmentAmount { get; set; }
        public int NoOfInstallment { get; set; }
        public System.DateTime InstallmentStartDate { get; set; }
        public string Remarks { get; set; }
        public int ApprovalStatus { get; set; }
        public Nullable<int> FK_PreparedBy { get; set; }
        public Nullable<int> FK_ApprovedBy { get; set; }
        public int FK_BranchID { get; set; }
        public int FK_YearID { get; set; }
        public int FK_CompanyID { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsClosed { get; set; }
    
        public virtual TBL_MP_Admin_UserList TBL_MP_Admin_UserList { get; set; }
        public virtual TBL_MP_HR_LoanRequestApplication TBL_MP_HR_LoanRequestApplication { get; set; }
        public virtual TBL_MP_Master_Employee TBL_MP_Master_Employee { get; set; }
    }
}
