//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_Master_UserList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MP_Master_UserList()
        {
            this.CheckList_Master = new HashSet<CheckList_Master>();
            this.TBL_MP_CRM_SalesEnquiry_Attachments = new HashSet<TBL_MP_CRM_SalesEnquiry_Attachments>();
            this.TBL_MP_CRM_SalesOrder_Attachment = new HashSet<TBL_MP_CRM_SalesOrder_Attachment>();
            this.TBL_MP_CRM_SalesQuotation_Attachments = new HashSet<TBL_MP_CRM_SalesQuotation_Attachments>();
            this.TBL_MP_CRM_SM_SalesLead_Attachment = new HashSet<TBL_MP_CRM_SM_SalesLead_Attachment>();
            this.TBL_MP_Master_Employee_Attachment = new HashSet<TBL_MP_Master_Employee_Attachment>();
            this.TBL_MP_Master_Item = new HashSet<TBL_MP_Master_Item>();
            this.TBL_MP_Master_Item1 = new HashSet<TBL_MP_Master_Item>();
            this.TBL_MP_Master_Item_Attachments = new HashSet<TBL_MP_Master_Item_Attachments>();
            this.TBL_MP_Master_Warehouse = new HashSet<TBL_MP_Master_Warehouse>();
        }
    
        public int pk_UserListId { get; set; }
        public int fk_CategoryId { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> FK_Company_ID { get; set; }
        public Nullable<int> FK_Branch_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckList_Master> CheckList_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_CRM_SalesEnquiry_Attachments> TBL_MP_CRM_SalesEnquiry_Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_CRM_SalesOrder_Attachment> TBL_MP_CRM_SalesOrder_Attachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_CRM_SalesQuotation_Attachments> TBL_MP_CRM_SalesQuotation_Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_CRM_SM_SalesLead_Attachment> TBL_MP_CRM_SM_SalesLead_Attachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_Employee_Attachment> TBL_MP_Master_Employee_Attachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_Item> TBL_MP_Master_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_Item> TBL_MP_Master_Item1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_Item_Attachments> TBL_MP_Master_Item_Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_Warehouse> TBL_MP_Master_Warehouse { get; set; }
    }
}
