//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBl_MP_HR_SalaryHead
    {
        public int pK_SH_ID { get; set; }
        public int fK_Usrlst_SH_ID { get; set; }
        public int fk_Usrlst_HdrType_ID { get; set; }
        public int Sequence { get; set; }
        public int fk_Usrlst_HdNature_ID { get; set; }
        public bool IsActive { get; set; }
        public int FK_BranchID { get; set; }
        public int FK_CompanyID { get; set; }
        public int FK_YearID { get; set; }
        public Nullable<bool> isForSalaryCalculation { get; set; }
    }
}
