//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_Master_Country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MP_Master_Country()
        {
            this.TBL_MP_Admin_Branch_Master = new HashSet<TBL_MP_Admin_Branch_Master>();
            this.TBL_MP_CRM_SalesEnquiry = new HashSet<TBL_MP_CRM_SalesEnquiry>();
            this.TBL_MP_Master_BankBranch = new HashSet<TBL_MP_Master_BankBranch>();
            this.TBL_MP_Master_City = new HashSet<TBL_MP_Master_City>();
            this.Tbl_MP_Master_Party_Address = new HashSet<Tbl_MP_Master_Party_Address>();
            this.TBL_MP_Master_State = new HashSet<TBL_MP_Master_State>();
        }
    
        public int pk_CountryId { get; set; }
        public string CountryName { get; set; }
        public string ISDCode { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencyCode { get; set; }
        public string Denomination { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> FK_CompanyID { get; set; }
        public Nullable<int> FK_BranchID { get; set; }
        public Nullable<int> Upto_Decimal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Admin_Branch_Master> TBL_MP_Admin_Branch_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_CRM_SalesEnquiry> TBL_MP_CRM_SalesEnquiry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_BankBranch> TBL_MP_Master_BankBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_City> TBL_MP_Master_City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MP_Master_Party_Address> Tbl_MP_Master_Party_Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_State> TBL_MP_Master_State { get; set; }
    }
}
