//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_HR_PayslipMaster
    {
        public int PayslipID { get; set; }
        public int FK_EmployeeID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string PayslipMonth { get; set; }
        public string PayslipJSON { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<int> FK_ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDatetime { get; set; }
        public decimal BasicSalary { get; set; }
        public decimal TotalAllounces { get; set; }
        public decimal TotalDeductions { get; set; }
        public decimal GrossSalary { get; set; }
        public decimal NetSalary { get; set; }
    
        public virtual TBL_MP_Master_Employee TBL_MP_Master_Employee { get; set; }
    }
}
