//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_Admin_Branch_Master
    {
        public int pk_BranchId { get; set; }
        public Nullable<int> fk_companyID { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public Nullable<int> fk_CountryId { get; set; }
        public Nullable<int> fk_StateId { get; set; }
        public Nullable<int> fk_CityId { get; set; }
        public Nullable<int> fk_AreaID { get; set; }
        public string Address { get; set; }
        public string Pincode { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string TelNo { get; set; }
        public string FaxNo { get; set; }
        public string TanNo { get; set; }
        public Nullable<bool> Is_SalesTaxReg { get; set; }
        public string VatTinNo { get; set; }
        public Nullable<System.DateTime> VatTinDate { get; set; }
        public string CstTinNo { get; set; }
        public Nullable<System.DateTime> CstTinDate { get; set; }
        public string Sentence { get; set; }
        public Nullable<bool> Is_STaxReg { get; set; }
        public string STaxNo { get; set; }
        public Nullable<System.DateTime> STaxDate { get; set; }
        public Nullable<bool> Is_IncomeTaxReg { get; set; }
        public string PanNo { get; set; }
        public Nullable<System.DateTime> PanDate { get; set; }
        public Nullable<bool> Is_PFReg { get; set; }
        public string PFAccNo { get; set; }
        public Nullable<System.DateTime> PFAccDate { get; set; }
        public Nullable<bool> Is_ESICReg { get; set; }
        public string ESICAccNo { get; set; }
        public Nullable<System.DateTime> ESICAccDate { get; set; }
        public Nullable<bool> Is_ExciseReg { get; set; }
        public string ECCNo { get; set; }
        public string PLANo { get; set; }
        public string Range { get; set; }
        public string RangeAddress { get; set; }
        public string Division { get; set; }
        public string DivisionAddress { get; set; }
        public string Commissionerate { get; set; }
        public string CommissionerateAddress { get; set; }
        public Nullable<int> IsExempted { get; set; }
        public string Limit { get; set; }
        public Nullable<int> MaxID { get; set; }
        public Nullable<bool> Is_Flagship { get; set; }
        public Nullable<int> FK_PreparedBy { get; set; }
        public Nullable<int> FK_ApprovedBy { get; set; }
        public Nullable<int> FK_CheckedBy { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<byte> IsHO { get; set; }
        public Nullable<int> FK_Currency_ID { get; set; }
        public string PrefixName { get; set; }
        public string GSTIN { get; set; }
    
        public virtual TBL_MP_Master_City TBL_MP_Master_City { get; set; }
        public virtual TBL_MP_Master_Country TBL_MP_Master_Country { get; set; }
        public virtual TBL_MP_Master_State TBL_MP_Master_State { get; set; }
    }
}
