//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_Master_Bank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MP_Master_Bank()
        {
            this.TBL_MP_Master_BankBranch = new HashSet<TBL_MP_Master_BankBranch>();
            this.TBL_MP_Master_Employee = new HashSet<TBL_MP_Master_Employee>();
            this.Tbl_MP_Master_Party_BankDetail = new HashSet<Tbl_MP_Master_Party_BankDetail>();
        }
    
        public int PK_BankID { get; set; }
        public string BankName { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_BankBranch> TBL_MP_Master_BankBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_Employee> TBL_MP_Master_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MP_Master_Party_BankDetail> Tbl_MP_Master_Party_BankDetail { get; set; }
    }
}
