//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_Admin_Company_Master
    {
        public int PK_CompanyID { get; set; }
        public string CompanyCode { get; set; }
        public string Company_name { get; set; }
        public string Address { get; set; }
        public string PinCode { get; set; }
        public int FK_CountryID { get; set; }
        public int FK_StateID { get; set; }
        public int FK_CityID { get; set; }
        public int FK_AreaID { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string PLA { get; set; }
        public string PhoneNo { get; set; }
        public string FaxNo { get; set; }
        public string ECC_NO { get; set; }
        public string TIN_NO { get; set; }
        public string PAN_NO { get; set; }
        public string GST_NO { get; set; }
        public string IEC_CODE { get; set; }
        public string RangeNO { get; set; }
        public string RangeAdd { get; set; }
        public string RangeCode { get; set; }
        public string DivisionCode { get; set; }
        public string DivisionNo { get; set; }
        public string DivisionAdd { get; set; }
        public string Commissionerate { get; set; }
        public string CommissionerateAdd { get; set; }
        public string LogoPath { get; set; }
        public string Abbreviation { get; set; }
        public byte[] LogoImage { get; set; }
        public string ShiftTimeFrom { get; set; }
        public string ShiftTimeTo { get; set; }
        public bool IsDelete { get; set; }
    }
}
