//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_Master_Employee_Authority
    {
        public int EmployeeAuthorityID { get; set; }
        public int FK_EmployeeID { get; set; }
        public int FK_AuthorityID { get; set; }
    }
}
