//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_PMC_ProjectMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MP_PMC_ProjectMaster()
        {
            this.TBL_MP_CRM_SalesOrder = new HashSet<TBL_MP_CRM_SalesOrder>();
            this.TBL_MP_HR_ManualAttendance_Master = new HashSet<TBL_MP_HR_ManualAttendance_Master>();
            this.TBL_MP_PMC_Project_Planning = new HashSet<TBL_MP_PMC_Project_Planning>();
        }
    
        public int PK_ProjectID { get; set; }
        public string ProjectNumber { get; set; }
        public System.DateTime ProjectDate { get; set; }
        public string ProjectName { get; set; }
        public int FK_ProjectStatusID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> BillingClientID { get; set; }
        public int BillingClientAddressID { get; set; }
        public Nullable<int> SiteClientID { get; set; }
        public int SiteClientAddressID { get; set; }
        public bool IsActive { get; set; }
        public int FK_YearID { get; set; }
        public int FK_BranchID { get; set; }
        public int FK_CompanyID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDatetime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeleteDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_CRM_SalesOrder> TBL_MP_CRM_SalesOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_HR_ManualAttendance_Master> TBL_MP_HR_ManualAttendance_Master { get; set; }
        public virtual Tbl_MP_Master_Party Tbl_MP_Master_Party { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_PMC_Project_Planning> TBL_MP_PMC_Project_Planning { get; set; }
    }
}
