//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_User_Master
    {
        public int PK_UserID { get; set; }
        public Nullable<int> FK_EmployeeID { get; set; }
        public Nullable<int> FK_BranchId { get; set; }
        public string LoginId { get; set; }
        public string LoginPassword { get; set; }
        public string EmailPassword { get; set; }
        public Nullable<int> FK_RoleId { get; set; }
        public Nullable<System.DateTime> UM_LastLogin { get; set; }
        public Nullable<int> UM_IsLoggedIn { get; set; }
        public Nullable<System.DateTime> UM_LastLogOut { get; set; }
        public string UM_SessionID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UM_Remarks { get; set; }
        public Nullable<int> ISAuthorized { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
        public Nullable<int> FromDay { get; set; }
        public Nullable<int> ToDay { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> SecurityLevel { get; set; }
        public Nullable<int> Theme { get; set; }
        public string EmailSMS_CODE { get; set; }
        public Nullable<System.DateTime> CODE_GEN_Time { get; set; }
    
        public virtual TBL_MP_Master_Employee TBL_MP_Master_Employee { get; set; }
    }
}
