//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_Master_Employee_Qualification
    {
        public int EmployeeQualificationID { get; set; }
        public int FK_EmployeeId { get; set; }
        public string Qualification { get; set; }
        public string NameOfInstitute { get; set; }
        public string Grade { get; set; }
        public bool isActive { get; set; }
        public bool isChecked { get; set; }
    
        public virtual TBL_MP_Master_Employee TBL_MP_Master_Employee { get; set; }
    }
}
