//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_Master_Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MP_Master_Item()
        {
            this.TBL_MP_CRM_SalesOrder_ItemCharges = new HashSet<TBL_MP_CRM_SalesOrder_ItemCharges>();
            this.TBL_MP_CRM_SalesQuotation_ItemCharges = new HashSet<TBL_MP_CRM_SalesQuotation_ItemCharges>();
            this.TBL_MP_Master_Item_AssemblyChildItems = new HashSet<TBL_MP_Master_Item_AssemblyChildItems>();
            this.TBL_MP_Master_Item_Attachments = new HashSet<TBL_MP_Master_Item_Attachments>();
            this.TBL_MP_Master_Item_Suppliers = new HashSet<TBL_MP_Master_Item_Suppliers>();
        }
    
        public int Pk_ItemID { get; set; }
        public Nullable<int> Fk_UserList_ItemType_ID { get; set; }
        public Nullable<int> Fk_InvCategory_ID { get; set; }
        public bool IsAssembly { get; set; }
        public string ItemCode { get; set; }
        public string HSNCode { get; set; }
        public string Item_Name { get; set; }
        public string Long_Description { get; set; }
        public string PartNumber { get; set; }
        public Nullable<int> Fk_UserList_BaseUOM_ID { get; set; }
        public Nullable<int> Fk_UserList_PurchaseUOM_ID { get; set; }
        public string ImageFileName { get; set; }
        public string UniqueString { get; set; }
        public Nullable<int> FK_ApprovedBy { get; set; }
        public Nullable<int> FK_CheckedBy { get; set; }
        public Nullable<int> FK_YearID { get; set; }
        public Nullable<int> FK_BranchID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeleteDatetime { get; set; }
        public string DeleteRemarks { get; set; }
    
        public virtual TBL_MP_Admin_UserList TBL_MP_Admin_UserList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_CRM_SalesOrder_ItemCharges> TBL_MP_CRM_SalesOrder_ItemCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_CRM_SalesQuotation_ItemCharges> TBL_MP_CRM_SalesQuotation_ItemCharges { get; set; }
        public virtual TBL_MP_Master_Inventory_Category TBL_MP_Master_Inventory_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_Item_AssemblyChildItems> TBL_MP_Master_Item_AssemblyChildItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_Item_Attachments> TBL_MP_Master_Item_Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_Item_Suppliers> TBL_MP_Master_Item_Suppliers { get; set; }
        public virtual TBL_MP_Master_UserList TBL_MP_Master_UserList { get; set; }
        public virtual TBL_MP_Master_UserList TBL_MP_Master_UserList1 { get; set; }
    }
}
