//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MP_Master_Party
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_MP_Master_Party()
        {
            this.TBL_MP_CRM_SalesEnquiry = new HashSet<TBL_MP_CRM_SalesEnquiry>();
            this.TBL_MP_CRM_SalesOrder = new HashSet<TBL_MP_CRM_SalesOrder>();
            this.TBL_MP_CRM_SalesOrder_ItemCharges = new HashSet<TBL_MP_CRM_SalesOrder_ItemCharges>();
            this.TBL_MP_CRM_SalesQuotation = new HashSet<TBL_MP_CRM_SalesQuotation>();
            this.TBL_MP_CRM_SalesQuotation_ItemCharges = new HashSet<TBL_MP_CRM_SalesQuotation_ItemCharges>();
            this.TBL_MP_CRM_SM_SalesLead = new HashSet<TBL_MP_CRM_SM_SalesLead>();
            this.TBL_MP_Master_Item_Suppliers = new HashSet<TBL_MP_Master_Item_Suppliers>();
            this.Tbl_MP_Master_Party_Address = new HashSet<Tbl_MP_Master_Party_Address>();
            this.Tbl_MP_Master_Party_BankDetail = new HashSet<Tbl_MP_Master_Party_BankDetail>();
            this.Tbl_MP_Master_PartyContact_Detail = new HashSet<Tbl_MP_Master_PartyContact_Detail>();
            this.TBL_MP_PMC_ProjectMaster = new HashSet<TBL_MP_PMC_ProjectMaster>();
        }
    
        public int PK_PartyId { get; set; }
        public Nullable<int> FK_PartyType { get; set; }
        public string PartyType { get; set; }
        public string PartyCode { get; set; }
        public string PartyName { get; set; }
        public Nullable<int> FK_AccountManager { get; set; }
        public Nullable<int> FK_ReferredBy { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> FK_Category { get; set; }
        public Nullable<int> FK_IndustryType { get; set; }
        public Nullable<int> FK_Type { get; set; }
        public string GSTNO { get; set; }
        public string PANNo { get; set; }
        public string VATTIN { get; set; }
        public string CSTTIN { get; set; }
        public string STNo { get; set; }
        public string Website { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> FK_ApprovedBy { get; set; }
        public Nullable<int> FK_CompanyID { get; set; }
        public Nullable<int> Fk_BranchID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeleteDateTime { get; set; }
        public string DeleteRemarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_CRM_SalesEnquiry> TBL_MP_CRM_SalesEnquiry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_CRM_SalesOrder> TBL_MP_CRM_SalesOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_CRM_SalesOrder_ItemCharges> TBL_MP_CRM_SalesOrder_ItemCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_CRM_SalesQuotation> TBL_MP_CRM_SalesQuotation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_CRM_SalesQuotation_ItemCharges> TBL_MP_CRM_SalesQuotation_ItemCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_CRM_SM_SalesLead> TBL_MP_CRM_SM_SalesLead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_Master_Item_Suppliers> TBL_MP_Master_Item_Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MP_Master_Party_Address> Tbl_MP_Master_Party_Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MP_Master_Party_BankDetail> Tbl_MP_Master_Party_BankDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MP_Master_PartyContact_Detail> Tbl_MP_Master_PartyContact_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MP_PMC_ProjectMaster> TBL_MP_PMC_ProjectMaster { get; set; }
    }
}
