//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_PMC_Project_CheckList
    {
        public int PK_ProjectCheckListID { get; set; }
        public Nullable<int> FK_ProjectID { get; set; }
        public string ProjectChecklist { get; set; }
    }
}
