//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_CRM_SalesEnquiry_BOQ
    {
        public int DESIGN_BOQ_ID { get; set; }
        public string BOQ_NUMBER { get; set; }
        public int ENQUIRY_ID { get; set; }
        public string BOQ_DESIGN_OBJECT { get; set; }
        public Nullable<int> BOQ_DESIGN_OBJECT_CREATED_BY { get; set; }
        public Nullable<System.DateTime> BOQ_DESIGN_OBJECT_CREATED_DATE { get; set; }
    }
}
