//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_Master_Warehouse
    {
        public int PK_WarehouseID { get; set; }
        public System.DateTime Entry_Date { get; set; }
        public string Warehouse_Code { get; set; }
        public string Warehouse_Name { get; set; }
        public string OfficeLocation { get; set; }
        public string Warehouse_Address { get; set; }
        public string WarehouseArea { get; set; }
        public Nullable<int> FK_UOM { get; set; }
        public int FK_Incharge { get; set; }
        public string Remark { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> FK_CompanyID { get; set; }
        public Nullable<int> FK_YearID { get; set; }
        public Nullable<int> FK_BranchID { get; set; }
    
        public virtual TBL_MP_Master_Employee TBL_MP_Master_Employee { get; set; }
        public virtual TBL_MP_Master_UserList TBL_MP_Master_UserList { get; set; }
    }
}
