//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MP_Master_Employee_MedicalDetail
    {
        public int Pk_EmpMedicalId { get; set; }
        public int fk_EmployeeId { get; set; }
        public string MedicalName { get; set; }
        public string CardNo { get; set; }
        public string CardType { get; set; }
        public string CompanyName { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
        public int FK_UL_RelationID { get; set; }
    
        public virtual TBL_MP_Admin_UserList TBL_MP_Admin_UserList { get; set; }
        public virtual TBL_MP_Master_Employee TBL_MP_Master_Employee { get; set; }
    }
}
