//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAttendanceRegister
    {
        public int PK_AttendanceID { get; set; }
        public System.DateTime AttendDate { get; set; }
        public int FK_EmployeeID { get; set; }
        public string EmployeeDescription { get; set; }
        public System.DateTime AttendInTime { get; set; }
        public System.DateTime AttendOutTime { get; set; }
        public string Duration { get; set; }
        public int AttendanceType { get; set; }
        public string AttendanceTypeName { get; set; }
        public Nullable<int> FK_CostCenterId { get; set; }
        public string ProjectName { get; set; }
        public bool AtWarehouse { get; set; }
        public int FK_PreparedBy { get; set; }
        public string PreparedBy { get; set; }
        public Nullable<int> FK_ApprovedBy { get; set; }
        public string ApprovedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string AttendanceRemarks { get; set; }
        public Nullable<int> FK_UserList_LeaveFormTypeID { get; set; }
        public string LeaveFormTypeName { get; set; }
        public Nullable<int> FK_LeaveTypeID { get; set; }
        public string LeaveTypeName { get; set; }
        public int FK_YearId { get; set; }
        public int FK_BranchId { get; set; }
        public int FK_CompanyId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> isLeaveRejected { get; set; }
        public Nullable<int> fk_UL_Cat_Id { get; set; }
        public string CategoryDesc { get; set; }
        public Nullable<int> FK_DepartmentId { get; set; }
        public string DepartmentName { get; set; }
    }
}
