//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLeaveApplication
    {
        public int PK_LeaveApplicationID { get; set; }
        public string ApplicationNo { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<System.DateTime> FromTime { get; set; }
        public Nullable<System.DateTime> ToTime { get; set; }
        public int FK_EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public int PreparedBy { get; set; }
        public string PreparedByName { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public int FK_UserList_LeaveFormTypeID { get; set; }
        public string LeaveFormTypeName { get; set; }
        public int fK_UsrLst_LeaveTypeID { get; set; }
        public string LeaveTypeName { get; set; }
        public int FK_UserList_ApprovalStatusID { get; set; }
        public string StatusDescription { get; set; }
        public int FK_RequestTo { get; set; }
        public string RequestTo { get; set; }
        public Nullable<int> FK_ApprovedBy { get; set; }
        public string ApprovedByName { get; set; }
        public Nullable<System.DateTime> Approval_Date { get; set; }
        public int FK_YearId { get; set; }
        public int FK_BranchId { get; set; }
        public int FK_CompanyId { get; set; }
        public string Remarks { get; set; }
        public bool IsDeleted { get; set; }
    }
}
