//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vMasterParty
    {
        public int PK_PartyId { get; set; }
        public string PartyType { get; set; }
        public string PartyCode { get; set; }
        public string PartyName { get; set; }
        public Nullable<int> FK_IndustryType { get; set; }
        public string Description1 { get; set; }
        public string GSTNO { get; set; }
        public string PANNo { get; set; }
        public string VATTIN { get; set; }
        public string CSTTIN { get; set; }
        public string STNo { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> FK_ApprovedBy { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<int> FK_CompanyID { get; set; }
        public Nullable<int> Fk_BranchID { get; set; }
    }
}
