//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vMasterItem
    {
        public int Pk_ItemID { get; set; }
        public Nullable<int> Fk_UserList_ItemType_ID { get; set; }
        public string Item_Type { get; set; }
        public Nullable<int> Fk_InvCategory_ID { get; set; }
        public string Category { get; set; }
        public string Category_Description { get; set; }
        public string ItemCode { get; set; }
        public string HSNCode { get; set; }
        public string Item_Name { get; set; }
        public string Long_Description { get; set; }
        public string PartNumber { get; set; }
        public Nullable<int> Fk_UserList_BaseUOM_ID { get; set; }
        public string Base_UOM { get; set; }
        public Nullable<int> Fk_UserList_PurchaseUOM_ID { get; set; }
        public string Purchase_UOM { get; set; }
        public string ImageFileName { get; set; }
        public Nullable<int> FK_ApprovedBy { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<int> FK_CheckedBy { get; set; }
        public string CheckedBy { get; set; }
        public Nullable<int> FK_YearID { get; set; }
        public Nullable<int> FK_BranchID { get; set; }
    }
}
