//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSalaryHead
    {
        public int SalaryHeadID { get; set; }
        public string SalaryHeadName { get; set; }
        public int SalaryHeadTypeID { get; set; }
        public string SalaryHeadTypeName { get; set; }
    }
}
