//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSalesOrder
    {
        public int PK_SalesOrderID { get; set; }
        public string SalesOrderNo { get; set; }
        public System.DateTime SalesOrderDate { get; set; }
        public int FK_POSource { get; set; }
        public string PO_Source { get; set; }
        public int FK_SalesOrderStatus { get; set; }
        public string Sales_Orderd_Status { get; set; }
        public int FK_SalesOrderType { get; set; }
        public string Sales_Order_Type { get; set; }
        public Nullable<decimal> MaterialSupplyFinalAmount { get; set; }
        public Nullable<decimal> InstallationFinalAmount { get; set; }
        public Nullable<decimal> OrderFinalAmount { get; set; }
        public string MaterialSupplyPONo { get; set; }
        public string InstallationServicePONo { get; set; }
        public Nullable<int> FK_QuotationID { get; set; }
        public string Quotation_No { get; set; }
        public Nullable<System.DateTime> Quotation_Date { get; set; }
        public Nullable<int> Quotation_ValidDays { get; set; }
        public string Remarks { get; set; }
        public int FK_ClientID { get; set; }
        public string PartyName { get; set; }
        public Nullable<int> FK_ProjectID { get; set; }
        public string ProjectNumber { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> FK_ApprovedBy { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<int> FK_BOQRepresentativeID { get; set; }
        public string BOQRepresentativeID { get; set; }
        public int FK_BranchID { get; set; }
        public int FK_YearID { get; set; }
        public int FK_CompanyID { get; set; }
    }
}
